[package]
name = "watchexec"
version = "1.10.0"
authors = ["Matt Green <mattgreenrocks@gmail.com>"]
description = "Executes commands in response to file modifications"
documentation = "https://github.com/watchexec/watchexec"
homepage = "https://github.com/watchexec/watchexec"
repository = "https://github.com/watchexec/watchexec"
readme = "README.md"
keywords = ["watcher", "inotify", "fsevents", "kqueue"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
appveyor = { repository = "watchexec/watchexec" }
travis-ci = { repository = "watchexec/watchexec" }

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[dependencies]
glob = "0.2.11"
globset = "0.4.1"
lazy_static = "1.1.0"
log = "0.4.4"
notify = "4.0.7"

[dev-dependencies]
mktemp = "0.3.1"

[dependencies.clap]
version = "2.32.0"
default-features = false
features = ["wrap_help"]

[dependencies.env_logger]
version = "0.5.12"
default-features = false
features = []

[target.'cfg(unix)'.dependencies]
nix = "0.11.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"

[[bin]]
name = "watchexec"
doc = false
