[package]
name = "watchexec"
version = "1.8.5"
authors = ["Matt Green <mattgreenrocks@gmail.com>"]
description = "Executes commands in response to file modifications"
documentation = "https://github.com/mattgreen/watchexec"
homepage = "https://github.com/mattgreen/watchexec"
repository = "https://github.com/mattgreen/watchexec"
readme = "README.md"
keywords = ["watcher", "inotify", "fsevents", "kqueue"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[dependencies]
glob = "0.2.11"
globset = "0.2"
lazy_static = "0.2.8"
log = "0.3.8"
notify = "4.0"

[dev-dependencies]
mktemp = "0.3.1"

[dependencies.clap]
version = "2.26"
default-features = false
features = ["wrap_help"]

[dependencies.env_logger]
version = "0.4"
default-features = false
features = []

[target.'cfg(unix)'.dependencies]
nix = "0.9"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"

[[bin]]
name = "watchexec"
doc = false
