[package]
name = "watchexec"
version = "1.12.0"
authors = ["Matt Green <mattgreenrocks@gmail.com>"]
description = "Executes commands in response to file modifications"
documentation = "https://github.com/watchexec/watchexec"
homepage = "https://github.com/watchexec/watchexec"
repository = "https://github.com/watchexec/watchexec"
readme = "README.md"
keywords = ["watcher", "inotify", "fsevents", "kqueue"]
categories = ["command-line-utilities"]
license = "Apache-2.0"
exclude = ["/ci/*", "/pkg/*", "/.travis.yml", "/Makefile", "/appveyor.yml"]
edition = "2018"

[badges]
appveyor = { repository = "watchexec/watchexec" }
travis-ci = { repository = "watchexec/watchexec" }

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[dependencies]
glob = "0.3.0"
globset = "0.4.1"
lazy_static = "1.1.0"
log = "0.4.4"
notify = "4.0.13"
derive_builder = "0.9.0"
walkdir = "2.3.1"

[dependencies.clap]
version = "2.32.0"
default-features = false
features = ["wrap_help"]

[dependencies.env_logger]
version = "0.7.1"
default-features = false
features = []

[target.'cfg(unix)'.dependencies]
nix = "0.15.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.8"
features = ["ioapiset", "jobapi2", "tlhelp32"]

[[bin]]
name = "watchexec"
doc = false
