name: Tag a release
on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  make-tag:
    runs-on: ubuntu-latest
    # because only bors can push to main, and it squashes, only PRs
    # that are named `release: {crate-name} v{version}` will get tagged!
    # the commit message will look like: `release: {crate-name} v{version} (#{pr-number})`
    if: "startsWith(github.event.head_commit.message, 'release: ')"

    outputs:
      tag_name: ${{ steps.extract.outputs.tag }}
    steps:
      - name: Extract tag from commit message
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          set -euxo pipefail

          message="$(head -n1 <<< "$COMMIT_MESSAGE")"
          crate="$(cut -d ' ' -f 2 <<< "${message}")"
          version="$(cut -d ' ' -f 3 <<< "${message}")"
          echo "CUSTOM_TAG=${crate}-${version}" >> $GITHUB_ENV
          echo "::set-output name=tag::${crate}-${version}"

      - uses: actions/checkout@v2
      - name: Push release tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.CUSTOM_TAG }}
          tag_prefix: ''

  release-cli:
    needs: make-tag
    if: "startsWith(needs.make-tag.outputs.tag_name, 'cli-v')"
    uses: ./.github/workflows/release-cli.yml
    secrets: inherit
